@startuml
left to right direction
skinparam packageStyle rectangle

actor "Пользователь" as U

rectangle "FinanceBuddy" {
  usecase "Добавить операцию" as UC1
  usecase "Редактировать операцию" as UC2
  usecase "Удалить операцию" as UC3
  usecase "Просмотреть список операций" as UC4
  usecase "Посмотреть сводку" as UC5
  usecase "Управлять категориями" as UC6
}

U --> UC1
U --> UC2
U --> UC3
U --> UC4
U --> UC5
U --> UC6
@enduml
